// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK2h9vjRs7f5yvZFO_KiV-8B3q00iseTU',
    appId: '1:1097120326703:web:7d4610461234078b4052da',
    messagingSenderId: '1097120326703',
    projectId: 'flutteruygulamalar',
    authDomain: 'flutteruygulamalar.firebaseapp.com',
    storageBucket: 'flutteruygulamalar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Gvihnyo3nDoPgDSO5vrD4uG92w0MjcE',
    appId: '1:1097120326703:android:4691b711fa126fb84052da',
    messagingSenderId: '1097120326703',
    projectId: 'flutteruygulamalar',
    storageBucket: 'flutteruygulamalar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfl8LcXVYtZ35m77lp-M4rdERWXbPFEo0',
    appId: '1:1097120326703:ios:8900aeaa41f111384052da',
    messagingSenderId: '1097120326703',
    projectId: 'flutteruygulamalar',
    storageBucket: 'flutteruygulamalar.appspot.com',
    iosClientId: '1097120326703-4cmijadp32db0gt3fcvasa4i4a7q1v72.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfl8LcXVYtZ35m77lp-M4rdERWXbPFEo0',
    appId: '1:1097120326703:ios:8900aeaa41f111384052da',
    messagingSenderId: '1097120326703',
    projectId: 'flutteruygulamalar',
    storageBucket: 'flutteruygulamalar.appspot.com',
    iosClientId: '1097120326703-4cmijadp32db0gt3fcvasa4i4a7q1v72.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasedeneme',
  );
}
